name: sentra_gps
description: Plataforma GPS para motos - SentraSecurity, Cartagena
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP y sesión con Traccar
  http: ^1.2.2
  cookie_jar: ^4.0.8
  dio: ^5.4.3
  dio_cookie_manager: ^3.1.1

  # WebSocket tiempo real
  web_socket_channel: ^2.4.5

  # Mapa (OpenStreetMap, sin API key)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # State management
  provider: ^6.1.2

  # Almacenamiento local
  shared_preferences: ^2.3.2

  # Notificaciones push locales
  flutter_local_notifications: ^17.2.3

  # Utilidades
  intl: ^0.19.0
  timeago: ^3.6.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
