"""device commands

Revision ID: e73c3182e7da
Revises: b3ab68daba45
Create Date: 2026-07-05 10:01:02.646863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e73c3182e7da'
down_revision: Union[str, None] = 'b3ab68daba45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_commands_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('command_password_enc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('command_password_enc')
        batch_op.drop_column('sim_phone')

    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_commands_vehicle_id'))

    op.drop_table('device_commands')
    # ### end Alembic commands ###
